# Generated by Django 3.0.5 on 2024-12-08 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
