# Generated by Django 3.0.5 on 2024-12-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
